server:
  port: 8080

debug: true

spring:

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-service

  datasource:
    url: jdbc:postgresql://postgres:5433/product_db
    username: product_user
    password: password
    driver-class-name: org.postgresql.Driver

    hikari:
      initialization-fail-timeout: 10000
    logging:
      level:
        org.hibernate: DEBUG
        org.springframework.jdbc: DEBUG

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect


  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml


app:
  kafka:
    topics:
      order-events: order-events
      order-created: order-created
      product-events: product-events
      user-events: user-events
      dead-letter-queue: order-events-dlq
    topic:
      partitions: 3
      replication-factor: 1
    retry:
      max-attempts: 3
      backoff-delay: 1000
      multiplier: 2.0
      max-delay: 10000
