#services:
#  postgres:
#    image: postgres:17-alpine
#    container_name: product-postgres
#    environment:
#      POSTGRES_DB: product_db
#      POSTGRES_USER: product_user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5433:5432"
#    volumes:
##      - postgres_data:/var/lib/postgresql/data
#      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#    networks:
#      - dco-network
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U product_user -d product_db" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  product-service:
#    build: ..
#    ports:
#      - "8081:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
#      SPRING_DATASOURCE_USERNAME: product_user
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - dco-network
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.6.1
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#    networks:
#      - dco-network
#
#  kafka:
#    image: confluentinc/cp-kafka:7.6.1
#    depends_on:
#      - zookeeper
#    ports:
#      - "29092:29092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_INTERNAL://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_INTERNAL://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#    networks:
#      - dco-network
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    depends_on:
#      - kafka
#    ports:
#      - "8086:8080"
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#    networks:
#      - dco-network
#
#volumes:
#  postgres_data:
#
#networks:
#  dco-network:
#    external: true
#    name: docker_dco-network
